### ISSUE TITLE
gulp deploy throwing below error.

### ISSUE THREAD

**Issue by msarm** [awslabs/aws-serverless-auth-reference-app#23]
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/desktop/aws-serverless-auth-reference-app/api/data'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.<anonymous> (/Users/desktop/aws-serverless-auth-reference-app/api/node_modules/rfr/lib/rfr.js:160:12)
    at Object.<anonymous> (/Users/desktop/aws-serverless-auth-reference-app/api/lambda/locations.js:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by justonian** [comment]
You first need to run npm install 3 different places to not encounter such an issue. These include /app, /api, and /api/data.

**Comment by lepirlouit** [comment]
there's no /api/data folder ...

**Comment by justonian** [comment]
Sorry...the third place to run gulp deploy is on /api/lambda in addition to /app and /api. The data.js file is in the lambda directory.
