### ISSUE TITLE
api create_sdk command fails

### ISSUE THREAD

**Issue by dscowan** [awslabs/aws-serverless-auth-reference-app#48]
The create_sdk command fails with the error below.  I did not see swagger included in the node packages.  What is the expectation here?

`
[22:04:11] Error: spawn swagger-codegen ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

**Comment by jcvalerio** [comment]
@dscowan did you have `swagger-codegen` installed? 

https://github.com/swagger-api/swagger-codegen

**Comment by dscowan** [comment]
I do.  I've only seen this problem on my windows machine.  Not my mac.
