### ISSUE TITLE
Cannot run gulp deploy

### ISSUE THREAD

**Issue by oanacioara** [awslabs/aws-serverless-auth-reference-app#50]
Hi!

I am trying to follow through the instructions at https://github.com/awslabs/aws-serverless-auth-reference-app/blob/master/Quickstart.md.

I got to the point where I have to run gulp deploy and I get the following error:

[2017-12-23T12:54:27.182Z]  INFO: spacefinder/96 on a032005c04ce: Creating CloudFormation stack...
[2017-12-23T12:54:27.731Z] ERROR: spacefinder/96 on a032005c04ce: 
    step failed { Error: getaddrinfo EAI_AGAIN cloudformation.us-east-1.amazonaws.com:443
        at Object._errnoException (util.js:1024:11)
        at errnoException (dns.js:55:15)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
      message: 'getaddrinfo EAI_AGAIN cloudformation.us-east-1.amazonaws.com:443',
      code: 'NetworkingError',
      errno: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'cloudformation.us-east-1.amazonaws.com',
      host: 'cloudformation.us-east-1.amazonaws.com',
      port: 443,
      region: 'us-east-1',
      retryable: true,
      time: 2017-12-23T12:54:27.729Z }
[12:54:27] 'create_cloudformation_stack' errored after 551 ms
[12:54:27] Error: getaddrinfo EAI_AGAIN cloudformation.us-east-1.amazonaws.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

This is the aws configuration:
AWS Access Key ID [****************GMNA]: 
AWS Secret Access Key [****************3tFs]: 
Default region name [us-east-1]: 
Default output format [None]: 

I also checked and my instance is deployed in a public subnet. 

Any thoughts on what might be the issue?

**Comment by Java1Guy** [comment]
Related, sort of, I got an error on deploy that there were no methods in the REST API... I think it needs a bit more sleep somewhere. I checked the API GW and it took a moment to appear. I ran the deploy again and it succeeded.

**Comment by justonian** [comment]
Hi there, @oanacioara-

Have you tried again to see if you're still encountering this issue? If you're using the Docker image on the EC2 instance referenced in the Quickstart guide, I've never seen the particular issue shown above come up as it would appear there's an issue contacting the cloudformation service from your EC2 VM. I'd suggest running a single ping out to an internet resource to test internet connectivity then try the command. Let me know if you're still having trouble.

@Java1Guy - I have rarely, but occasionally noticed that API GW can take a longer amount of time to be deployed than the sleep permits for an initial install. As you noticed, gulp deploy is idempotent so running it twice will allow the process to finish as expected. If you feel a particular fix would be best, feel free to submit a pull request. Otherwise, I can look to extend my sleep timer a bit longer to probably solve this
